ENV['VAGRANT_NO_PARALLEL'] = 'yes'

VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.hostmanager.enabled = true
  config.hostmanager.include_offline = true

  config.vm.provision :shell, path: "update-ubuntu-packages.sh"

  config.vm.define "controller" do |controller|
    controller.vm.box = 'ubuntu/focal64'
    controller.vm.hostname = 'controller'

    controller.vm.network :private_network, ip: "192.168.0.11"

    controller.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--memory", 512]
      v.customize ["modifyvm", :id, "--name", "controller"]
    end

    controller.vm.provision :shell, path: "install-ansible.sh"
    
  end

  config.vm.define "node" do |node|
    node.vm.box = 'ubuntu/focal64'
    node.vm.hostname = 'node'

    node.vm.network :private_network, ip: "192.168.0.12"

    node.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--memory", 1024]
      v.customize ["modifyvm", :id, "--name", "node"]
    end
  end
end