VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.ssh.insert_key = false
  config.ssh.forward_agent = true

  config.vm.provision :hosts do |provisioner|

      provisioner.add_host '192.168.56.101', ['controller']
      provisioner.add_host '192.168.56.102', ['node']

  end

  config.vm.define "controller" do |controller|
    controller.vm.box = 'ubuntu/bionic64'
    controller.vm.hostname = 'controller'

    controller.vm.network :private_network, ip: "192.168.56.101"
    controller.vm.network :forwarded_port, guest: 22, host: 10122, id: "ssh"

    controller.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 512]
      v.customize ["modifyvm", :id, "--name", "controller"]
    end

    controller.vm.provision :shell, path: "install-ansible.sh"
    
  end

  config.vm.define "node" do |node|
    node.vm.box = 'ubuntu/bionic64'
    node.vm.hostname = 'node'

    node.vm.network :private_network, ip: "192.168.56.102"
    node.vm.network :forwarded_port, guest: 22, host: 10222, id: "ssh"

    node.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 512]
      v.customize ["modifyvm", :id, "--name", "node"]
    end
  end

  config.vm.provision :shell, path: "update-ubuntu-packages.sh"

end